const multer = require("multer");
const express = require("express");
const cors = require("cors");
const csv = require("csv-parser");
const fs = require("fs");
const {
  validatePhone,
  validateDate,
  validatePayment
} = require("./validator");

const app = express();

app.use(cors());
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, "uploads/");
  },

  filename: function (req, file, cb) {
    cb(null, Date.now() + "-" + file.originalname);
  },
});

const upload = multer({ storage });

app.get("/", (req, res) => {
  res.send("Backend Running");
});
app.post("/upload", upload.single("file"), (req, res) => {
   const results = [];
  const requiredColumns = [
  "order_id",
  "product_name",
  "phone",
  "country",
  "date",
  "payment_mode"
];

 
  const firstLine = fs
  .readFileSync(req.file.path, "utf8")
  .split("\n")[0]
  .trim();

const uploadedColumns =
  firstLine.split(",");
  console.log(uploadedColumns);

const missingColumns =
  requiredColumns.filter(
    col =>
      !uploadedColumns.includes(col)
  );

if (missingColumns.length > 0) {

  return res.status(400).json({
    message:
      "Missing Required Columns",
    missingColumns
  });

}

  fs.createReadStream(req.file.path)
    .pipe(
      csv({
        
        headers: [
          "order_id",
          "product_name",
          "phone",
          "country",
          "date",
          "payment_mode"
        ],
        skipLines: 1
      })
    )
    .on("data", (data) => {

  if (data.phone === "phone") {
    return;
  }

  const isPhoneValid = validatePhone(
    data.phone,
    data.country
  );
  const isDateValid = validateDate(
  data.date
);

const isPaymentValid = validatePayment(
  data.payment_mode
);

data.dateStatus = isDateValid
  ? "Valid"
  : "Invalid";

data.paymentStatus = isPaymentValid
  ? "Valid"
  : "Invalid";

data.overallStatus =
  isPhoneValid &&
  isDateValid &&
  isPaymentValid
    ? "Valid"
    : "Invalid";
    if (!isPhoneValid) {
  data.errorReason =
    "Phone Number Error";
}

else if (!isDateValid) {
  data.errorReason =
    "Date Format Error";
}

else if (!isPaymentValid) {
  data.errorReason =
    "Payment Mode Error";
}

else {
  data.errorReason =
    "No Error";
}

  data.phoneStatus = isPhoneValid
    ? "Valid"
    : "Invalid";

  results.push(data);
})
    .on("end", () => {

      console.log(results);
      const validRecords = results.filter(
  row => row.overallStatus === "Valid"
);
const invalidRecords = results.filter(
  row => row.overallStatus === "Invalid"
);

const phoneErrors = results.filter(
  row => row.phoneStatus === "Invalid"
).length;

const dateErrors = results.filter(
  row => row.dateStatus === "Invalid"
).length;

const paymentErrors = results.filter(
  row => row.paymentStatus === "Invalid"
).length;

const qualityScore = Math.round(
  (validRecords.length / results.length) * 100
);

const report = `
XENO DATA VALIDATION REPORT

================================

Total Records: ${results.length}

Valid Records: ${validRecords.length}

Invalid Records: ${invalidRecords.length}

Phone Validation Errors: ${phoneErrors}

Date Validation Errors: ${dateErrors}

Payment Validation Errors: ${paymentErrors}

Data Quality Score: ${qualityScore}%

================================

Generated By:
Xeno Data Validator
`;

fs.writeFileSync(
  "output/validation_report.txt",
  report
);

const csvData = [
  "order_id,product_name,phone,country,date,payment_mode,phoneStatus,dateStatus,paymentStatus,overallStatus",

  ...validRecords.map(row =>
    `${row.order_id},${row.product_name},${row.phone},${row.country},${row.date},${row.payment_mode},${row.phoneStatus},${row.dateStatus},${row.paymentStatus},${row.overallStatus}`
  )
].join("\n");

fs.writeFileSync(
  "output/cleaned.csv",
  csvData
);
const chunkSize = 1;

for (let i = 0; i < results.length; i += chunkSize) {

  const chunk = results.slice(
    i,
    i + chunkSize
  );

  const chunkCsv = [
    "order_id,product_name,phone,country,date,payment_mode,phoneStatus,dateStatus,paymentStatus,overallStatus",
    ...chunk.map(row =>
      `${row.order_id},${row.product_name},${row.phone},${row.country},${row.date},${row.payment_mode},${row.phoneStatus},${row.dateStatus},${row.paymentStatus},${row.overallStatus}`
    )
  ].join("\n");

  fs.writeFileSync(
    `output/chunk_${i / chunkSize + 1}.csv`,
    chunkCsv
  );
}

res.json({
  message: "CSV Processed Successfully",
  data: results
});

    });

});
app.get("/download", (req, res) => {

  const filePath = "output/cleaned.csv";

  res.download(filePath);

});
app.get("/download-report", (req, res) => {

  const filePath =
    "output/validation_report.txt";

  res.download(filePath);

});
app.listen(5000, () => {
  console.log("Server Running On Port 5000");
});